### ISSUE TITLE
Docker does no more build on Fedora 30

### ISSUE THREAD

**Issue by FreshXOpenSource** [jpjodoin/sunshower#1]
Hi Jean-Philippe,

wanted to try out your version, but can not get it running on my FC30 box

```
[root@xyz sunshower]# ./build.sh
Sending build context to Docker daemon 347.1 kB
Step 1/15 : FROM erlang:22.3.4.1-alpine as base
Error parsing reference: "erlang:22.3.4.1-alpine as base" is not a valid repository/tag: invalid reference format
```

Any ideas,

thanks Kai

PS : did not see your hackaday mention until recently

**Comment by jpjodoin** [comment]
Hello Kai,
It could be an issue with your docker version. Which version do you have ? (`docker version`)

I am running version 18.09.3

Normally, you should be able to call 
`docker pull erlang:22.3.4.1-alpine`

I recommend installing the version directly from the docker repository as the one that usually comes with the OS is usually pretty old.

Cheers.

**Comment by FreshXOpenSource** [comment]
yes you are right, overnight i upgraded to FC32 and its runs now!

is there a simple way to run it without docker? i tried to manually run rebar3 compile but it always crashes (and im not an erl expert)

```
sunshower]# rebar3 compile
===> Failed creating providers. Run with DEBUG=1 for stacktrace or consult rebar3.crashdump.
```

cheers

**Comment by jpjodoin** [comment]
Yes, here are the step:
1) You will need Erlang 22.3
2) The latest version of rebar (probably what you have)
3)  You should define an env variable MELNOR_DEVICEID. Alternatively, you can just hardcode it in config/sys.config.src by changing 
`{default_deviceid, <<"${MELNOR_DEVICEID}">>}` to `{default_deviceid, <<"D01234AB01D0">>}` 

4) `sudo rebar3 shell ` (sudo is required here on ubuntu since we want to listen on port 80)

Can you post the output of `rebar3 --version` ?

Cheers.

**Comment by FreshXOpenSource** [comment]
```
[sunshower]# rpm -qa|grep erlang-22
erlang-22.3.4.2-1.fc32.x86_64
[sunshower]# rpm -qa|grep rebar
erlang-rebar3-3.11.1-3.fc32.noarch
[sunshower]# rebar3 --version
===> Failed creating providers. Run with DEBUG=1 for stacktrace or consult rebar3.crashdump.
[sunshower]# rebar3 shell
===> Failed creating providers. Run with DEBUG=1 for stacktrace or consult rebar3.crashdump.
```

Something seems really fishy here

**Comment by FreshXOpenSource** [comment]
```
[root@black sunshower]# DEBUG=1 rebar3 --version
===> error: undef [{relx,opt_spec_list,[],[]},
                          {rebar_prv_release,init,1,
                              [{file,
                                   "/builddir/build/BUILD/rebar3-3.11.1/src/rebar_prv_release.erl"},
                               {line,30}]},
                          {rebar_state,'-create_logic_providers/2-fun-0-',2,
                              [{file,
                                   "/builddir/build/BUILD/rebar3-3.11.1/src/rebar_state.erl"},
                               {line,479}]},
                          {lists,foldl,3,[{file,"lists.erl"},{line,1263}]},
                          {rebar_state,create_logic_providers,2,
                              [{file,
                                   "/builddir/build/BUILD/rebar3-3.11.1/src/rebar_state.erl"},
                               {line,478}]},
                          {rebar3,run_aux,2,
                              [{file,
                                   "/builddir/build/BUILD/rebar3-3.11.1/src/rebar3.erl"},
                               {line,161}]},
                          {rebar3,main,1,
                              [{file,
                                   "/builddir/build/BUILD/rebar3-3.11.1/src/rebar3.erl"},
                               {line,66}]},
                          {erl_eval,local_func,6,
                              [{file,"erl_eval.erl"},{line,567}]}]
===> Failed creating providers. Run with DEBUG=1 for stacktrace or consult rebar3.crashdump.
```

**Comment by FreshXOpenSource** [comment]
i think we can close this issue, the docker version is running and the other problem is not really sunshower related ... still maybe you an put up the non docker version into the docu.

thanks :)

**Comment by jpjodoin** [comment]
Yes, good idea. I will add it.

Cheers
